config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :destinations, :locations, :reviews
  end

  get 'admin/destination/:destination_id/new_location' => 'admin/locations#new', as: :admin_destination_new_location
  post 'admin/destination/:destination_id/locations' => 'admin/locations#create', as: :admin_destination_locations

  get 'admin/location/:location_id/new_review' => 'admin/reviews#new', as: :admin_location_new_review
  post 'admin/location/:location_id/reviews' => 'admin/reviews#create', as: :admin_location_reviews

  get 'admin/reviews/:id/status' => 'admin/reviews#status', as: :admin_review_status
end

app/models/destination.rb
class Destination < ActiveRecord::Base
  has_many :locations
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :destination
  has_many :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :location
end

app/controllers/admin/destinations_controller.rb
class Admin::DestinationsController < ApplicationController
  def index
    @destinations = Destination.all
  end

  def new
  end

  def create
    @destination = Destination.new(destination_params)

    if @destination.save
      flash[:success] = "Destination Created"
      redirect_to admin_destinations_path
    else
      render 'new'
    end
  end

  def show
    @destination = Destination.find(params[:id])
    @locations = @destination.locations
  end

  def destroy
    @destination = Destination.find(params[:id])
    @destination.destroy

    redirect_to admin_destinations_path
  end

  private

    def destination_params
      params.require(:destination).permit(:state, :city)
    end
end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < ApplicationController
  def index
    @locations = Location.all
  end

  def new
    @destination_id = params[:destination_id]
  end

  def create
    @destination = Destination.find(params[:location][:destination_id])
    @location = @destination.locations.build(location_params)

    if @location.save
      flash[:success] = "Location Created"
      redirect_to admin_destination_path(@destination)
    else
      render 'new'
    end
  end

  def show
    @location = Location.find(params[:id])
    @reviews = @location.reviews
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    redirect_to admin_locations_path
  end

  private

    def location_params
      params.require(:location).permit(:name, :city, :destination_id)
    end
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  def index
    @reviews = Location.find(params[:id]).reviews
    @location_id = params[:id]
  end

  def new
    @location_id = params[:location_id]
  end

  def create
    @location = Location.find(params[:review][:location_id])
    @review = @location.reviews.build(review_params)

    if @review.save
      flash[:success] = "Review Submitted"
      redirect_to admin_location_path(@location.id)
    else
      redirect_to admin_location_new_review_path(:location_id => @location.id)
    end
  end

  def status
    @review = Review.find(params[:id])

    @review.status == 'approve' ? @review.update(status: 'unapprove') : @review.update(status: 'approve')
    redirect_to admin_location_path(:id => @review.location_id)
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    redirect_to admin_location_path(:id => @review.location_id)
  end

  private

    def review_params
      params.require(:review).permit(:comment, :rating, :location_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  def index
    @destinations = Destination.all
  end

  def new
  end

  def create
    @destination = Destination.new(destination_params)

    if @destination.save
      flash[:success] = "Destination Created"
      redirect_to destinations_path
    else
      render 'new'
    end
  end

  def show
    @destination = Destination.find(params[:id])
    @locations = @destination.locations
  end

  def destroy
    @destination = Destination.find(params[:id])
    @destination.destroy

    redirect_to destinations_path
  end

  private

    def destination_params
      params.require(:destination).permit(:state, :city)
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.all
  end

  def new
    @destination_id = params[:destination_id]
  end

  def create
    @destination = Destination.find(params[:location][:destination_id])
    @location = @destination.locations.build(location_params)

    if @location.save
      flash[:success] = "Location Created"
      redirect_to destination_path(@destination)
    else
      render 'new'
    end
  end

  def show
    @location = Location.find(params[:id])
    @reviews = @location.reviews
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    redirect_to locations_path
  end

  private

    def location_params
      params.require(:location).permit(:name, :city, :destination_id)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Location.find(params[:id]).reviews
    @location_id = params[:id]
  end

  def new
    @location_id = params[:location_id]
  end

  def create
    @location = Location.find(params[:review][:location_id])
    @review = @location.reviews.build(review_params)

    if @review.save
      flash[:success] = "Review Submitted"
      redirect_to location_path(@location.id)
    else
      redirect_to location_new_review_path(:location_id => @location.id)
    end
  end

  private

    def review_params
      params.require(:review).permit(:comment, :rating, :location_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/admin/destinations/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-6">
      <h4>Destination</h4>
    </div>
    <div class="col-md-8 col-md-offset-2">
      <table class="table table-striped table-hover">
        <tr>
          <th>State</th>
          <th>City</th>
          <th></th>
        </tr>

        <% @destinations.each do |destination| %>
          <tr>
            <td> <%= destination.state %> </td>
            <td> <%= link_to destination.city, admin_destination_path(destination)%> </td>
            <td> <%= link_to "Delete", admin_destination_path(destination),
                     method: :delete,
                     data: {confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %></td>
          </tr>
        <% end %>
      </table>
    </div>
    <div class="col-md-4 col-md-offset-2">
      <%= link_to 'Add Destination', new_admin_destination_path , class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/admin/destinations/new.html.erb
<div class=container>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <h4>Add new Destination</h4>
    </div>
  </div>
<%= form_for :destination, url: admin_destinations_path,:html => {:class => "form-horizontal center"} do |f| %>

    <div class="form-group">
      <%= f.label :state,class: "col-md-4 control-label"  %>
      <div class="col-md-4">
        <%= f.text_field :state, class: "form-control" %>
      </div>
    </div>

  <div class="form-group">
    <%= f.label :city,class: "col-md-4 control-label"   %>
    <div class="col-md-4">
      <%= f.text_field :city, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-8 col-md-offset-4">
      <%= f.submit%>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-8 col-md-offset-4">
      <%= link_to "Back", admin_destinations_path  %>
    </div>
  </div>
<% end %>
</div>

app/views/admin/destinations/show.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-6 col-sm-offset-3 ">
      <table class="table">
        <tr>
          <td><strong>State</strong></td>
          <td><%= @destination.state %></td>
        </tr>
        <tr>
          <td><strong>City</strong></td>
          <td><%= @destination.city %></td>
        </tr>
        <tr>
          <td><%= link_to "Back", admin_destinations_path %></td>
          <td><%= link_to "Add Location", admin_destination_new_location_path(:destination_id => @destination.id ) %></td>
        </tr>
    </div>
  </div>
</div>


<div class="container">
  <div class="row">
    <div class="col-lg-3">
    </div>
    <div class="col-lg-6">
      <table class="table">
        <tr>
          <th>Location Name</th>
          <th>Location City</th>
        </tr>
        <% @locations.each do |location| %>
          <tr>
            <td> <%= link_to location.name, admin_location_path(location) %> </td>
            <td> <%= location.city %></td>
          </tr>
        <% end %>
    </div>
  </div>
</div>

app/views/admin/locations/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-6">
      <h4>Location</h4>
    </div>
    <div class="col-md-8 col-md-offset-2">
      <table class="table table-striped table-hover">
        <tr>
          <th>Name</th>
          <th>City</th>
          <th></th>
        </tr>

        <% @locations.each do |location| %>
          <tr>
            <td> <%= link_to location.name, location_path(location)%> </td>
            <td> <%= location.city %> </td>
            <td> <%= link_to "Delete", location_path(location),
                     method: :delete,
                     data: {confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %></td>
          </tr>
        <% end %>
      </table>
    </div>
    <div class="col-md-4 col-md-offset-2">
      <%= link_to 'Add Location', new_location_path , class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/admin/locations/new.html.erb
<div class=container>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <h4>Add new Location</h4>
    </div>
  </div>
<%= form_for :location, url: admin_destination_locations_path,:html => {:class => "form-horizontal center"} do |f| %>
    <%= f.hidden_field :destination_id, :value => @destination_id %>
    <div class="form-group">
      <%= f.label :name,class: "col-md-4 control-label"  %>
      <div class="col-md-4">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>

  <div class="form-group">
    <%= f.label :city,class: "col-md-4 control-label"   %>
    <div class="col-md-4">
      <%= f.text_field :city, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-8 col-md-offset-4">
      <%= f.submit%>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-8 col-md-offset-4">
      <%= link_to "Back", admin_destinations_path  %>
    </div>
  </div>
<% end %>
</div>

app/views/admin/locations/show.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-6 col-sm-offset-3 ">
      <table class="table">
        <tr>
          <td><strong>Name</strong></td>
          <td><%= @location.name %></td>
        </tr>
        <tr>
          <td><strong>City</strong></td>
          <td><%= @location.city %></td>
        </tr>
        <tr>
          <td><%= link_to "Back", admin_locations_path %></td>
          <td><%= link_to "Write Review", admin_location_new_review_path(:location_id => @location.id) %></td>
        </tr>
    </div>
  </div>
</div>


<div class="container">
  <div class="row">
    <div class="col-lg-3">
    </div>
    <div class="col-lg-6">
      <table class="table">
        <tr>
          <th>Comment</th>
          <th>Rating</th>
          <th></th>
          <th></th>
        </tr>
        <% @reviews.each do |review| %>
          <tr>
            <td> <%= review.comment %> </td>
            <td> <%= review.rating %></td>
            <td> <%= link_to review.status == 'approve' ? 'Unapprove' : 'Approve',
                     admin_review_status_path(review), class: "btn btn-primary btn-sm" %></td>
            <td> <%= link_to "Trash", admin_review_path(review),
                     method: :delete,
                     data: {confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %></td>
          </tr>
        <% end %>
    </div>
  </div>
</div>

app/views/admin/reviews/new.html.erb
<div class=container>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <h4>Write Review</h4>
    </div>
  </div>
<%= form_for :review, url: admin_location_reviews_path,:html => {:class => "form-horizontal center"} do |f| %>
    <%= f.hidden_field :location_id, :value => @location_id %>
    <div class="form-group">
      <%= f.label :comment,class: "col-md-4 control-label"  %>
      <div class="col-md-4">
        <%= f.text_field :comment, class: "form-control" %>
      </div>
    </div>

  <div class="form-group">
    <%= f.label :rating,class: "col-md-4 control-label"   %>
    <div class="col-md-4">
      <%= f.text_field :rating, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-8 col-md-offset-4">
      <%= f.submit%>
    </div>
  </div>
<% end %>
</div>

app/views/destinations/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-6">
      <h4>Destination</h4>
    </div>
    <div class="col-md-8 col-md-offset-2">
      <table class="table table-striped table-hover">
        <tr>
          <th>State</th>
          <th>City</th>
          <th></th>
        </tr>

        <% @destinations.each do |destination| %>
          <tr>
            <td> <%= destination.state %> </td>
            <td> <%= link_to destination.city, destination_path(destination)%> </td>
            <td> <%= link_to "Delete", destination_path(destination),
                     method: :delete,
                     data: {confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %></td>
          </tr>
        <% end %>
      </table>
    </div>
    <div class="col-md-4 col-md-offset-2">
      <%= link_to 'Add Destination', new_destination_path , class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/destinations/new.html.erb
<div class=container>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <h4>Add new Destination</h4>
    </div>
  </div>
<%= form_for :destination, url: destinations_path,:html => {:class => "form-horizontal center"} do |f| %>

    <div class="form-group">
      <%= f.label :state,class: "col-md-4 control-label"  %>
      <div class="col-md-4">
        <%= f.text_field :state, class: "form-control" %>
      </div>
    </div>

  <div class="form-group">
    <%= f.label :city,class: "col-md-4 control-label"   %>
    <div class="col-md-4">
      <%= f.text_field :city, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-8 col-md-offset-4">
      <%= f.submit%>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-8 col-md-offset-4">
      <%= link_to "Back", destinations_path  %>
    </div>
  </div>
<% end %>
</div>

app/views/destinations/show.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-6 col-sm-offset-3 ">
      <table class="table">
        <tr>
          <td><strong>State</strong></td>
          <td><%= @destination.state %></td>
        </tr>
        <tr>
          <td><strong>City</strong></td>
          <td><%= @destination.city %></td>
        </tr>
        <tr>
          <td><%= link_to "Back", destinations_path %></td>
          <td><%= link_to "Add Product", destination_new_location_path(:destination_id => @destination.id ) %></td>
        </tr>
    </div>
  </div>
</div>


<div class="container">
  <div class="row">
    <div class="col-lg-3">
    </div>
    <div class="col-lg-6">
      <table class="table">
        <tr>
          <th>Location Name</th>
          <th>Location City</th>
        </tr>
        <% @locations.each do |location| %>
          <tr>
            <td> <%= link_to location.name, location_path(location) %> </td>
            <td> <%= location.city %></td>
          </tr>
        <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
<head>
  <title>Trip</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/new.html.erb
<div class=container>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <h4>Add new Location</h4>
    </div>
  </div>
<%= form_for :location, url: destination_locations_path,:html => {:class => "form-horizontal center"} do |f| %>
    <%= f.hidden_field :destination_id, :value => @destination_id %>
    <div class="form-group">
      <%= f.label :name,class: "col-md-4 control-label"  %>
      <div class="col-md-4">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>

  <div class="form-group">
    <%= f.label :city,class: "col-md-4 control-label"   %>
    <div class="col-md-4">
      <%= f.text_field :city, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-8 col-md-offset-4">
      <%= f.submit%>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-8 col-md-offset-4">
      <%= link_to "Back", destinations_path  %>
    </div>
  </div>
<% end %>
</div>

app/views/locations/show.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-6 col-sm-offset-3 ">
      <table class="table">
        <tr>
          <td><strong>Name</strong></td>
          <td><%= @location.name %></td>
        </tr>
        <tr>
          <td><strong>City</strong></td>
          <td><%= @location.city %></td>
        </tr>
        <tr>
          <td><%= link_to "Back", locations_path %></td>
          <td><%= link_to "Write Review", location_new_review_path(:location_id => @location.id) %></td>
        </tr>
    </div>
  </div>
</div>


<div class="container">
  <div class="row">
    <div class="col-lg-3">
    </div>
    <div class="col-lg-6">
      <table class="table">
        <tr>
          <th>Comment</th>
          <th>Rating</th>
        </tr>
        <% @reviews.each do |review| %>
          <tr>
            <td> <%= review.comment %> </td>
            <td> <%= review.rating %></td>
          </tr>
        <% end %>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<div class=container>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <h4>Write Review</h4>
    </div>
  </div>
<%= form_for :review, url: location_reviews_path,:html => {:class => "form-horizontal center"} do |f| %>
    <%= f.hidden_field :location_id, :value => @location_id %>
    <div class="form-group">
      <%= f.label :comment,class: "col-md-4 control-label"  %>
      <div class="col-md-4">
        <%= f.text_field :comment, class: "form-control" %>
      </div>
    </div>

  <div class="form-group">
    <%= f.label :rating,class: "col-md-4 control-label"   %>
    <div class="col-md-4">
      <%= f.text_field :rating, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-8 col-md-offset-4">
      <%= f.submit%>
    </div>
  </div>
<% end %>
</div>